# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marnaudy <marnaudy@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/05/04 17:15:05 by marnaudy          #+#    #+#              #
#    Updated: 2022/06/07 07:58:20 by marnaudy         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME	=	megaphone

SRCS	=	megaphone.cpp

CC		=	c++

CFLAGS	=	-Wall -Wextra -Werror -std=c++98

RM		=	rm -f

all:		${NAME}

fclean:
			${RM} ${NAME}

re:			fclean all

.PHONY:		all fclean re
