#include <stdio.h>

int main(void)
{
	int	n;

	puts("");
	puts("too many/ too few args");
	n = printf("%s %p", "hello", "hi", "feifj");
	printf("\n%i\n", n);
	n = printf("%s %i", "hello");
	printf("\n%i\n", n);
	n = printf("%s %i", "hello", "hi");
	printf("\n%i\n", n);
	puts("");
	puts("Invalid specifier");
	n = printf("%s %b", "hello", "hi");
	printf("\n%i\n", n);
	n = printf("%s %0#b", "hello", "hi");
	printf("\n%i\n", n);
	puts("");
	puts("Missing specifier");
	n = printf("%%+04i", 123, 456);
	printf("\n%i\n", n);
	n = printf("%_%+04i", 123, 456);
	printf("\n%i\n", n);
	n = printf("%+04%+04i", 123, 456);
	printf("\n%i\n", n);
	puts("");
	puts("Invalid flag");
	n = printf("%_s", "hello");
	printf("\n%i\n", n);
	n = printf("%$i", 123);
	printf("\n%i\n", n);
	puts("");
	puts("Duplicate flag");
	n = printf("%++i", 123);
	printf("\n%i\n", n);
	n = printf("%  i", 123);
	printf("\n%i\n", n);
	puts("");
	puts("Width formatting");
	n = printf("%010i", 123);
	printf("\n%i\n", n);
	n = printf("%1 0i", 123);
	printf("\n%i\n", n);
	n = printf("%000000i", 123);
	printf("\n%i\n", n);
	n = printf("%1t0i", 123);
	printf("\n%i\n", n);
	n = printf("%1k0i", 123);
	printf("\n%i\n", n);
	puts("");
	puts("Precision formatting");
	n = printf("%.010i", 123);
	printf("\n%i\n", n);
	n = printf("%.1 0i", 123);
	printf("\n%i\n", n);
	n = printf("%.000000i", 123);
	printf("\n%i\n", n);
	n = printf("%.1t0i", 123);
	printf("\n%i\n", n);
	n = printf("%.1k0i", 123);
	printf("\n%i\n", n);
	puts("");
	puts("-0 precedence");
	n = printf("_%#0+12i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%#0-+12i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%#-0+12i_", 12345);
	printf("\n%i\n", n);
	puts("");
	puts("+ space precedence");
	n = printf("_%#0+ 12i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%#0 +12i_", 12345);
	printf("\n%i\n", n);
	puts("");
	puts("plus tests");
	n = printf("_%+i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%+d_", 12345);
	printf("\n%i\n", n);
	n = printf("_%+u_", 12345);
	printf("\n%i\n", n);
	n = printf("_%+x_", 12345);
	printf("\n%i\n", n);
	n = printf("_%+X_", 12345);
	printf("\n%i\n", n);
	n = printf("_%+c_", 'c');
	printf("\n%i\n", n);
	n = printf("_%+s_", "hello");
	printf("\n%i\n", n);
	puts("");
	puts("# tests");
	n = printf("_%#i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%#d_", 12345);
	printf("\n%i\n", n);
	n = printf("_%#u_", 12345);
	printf("\n%i\n", n);
	n = printf("_%#x_", 12345);
	printf("\n%i\n", n);
	n = printf("_%#X_", 12345);
	printf("\n%i\n", n);
	n = printf("_%#c_", 'c');
	printf("\n%i\n", n);
	n = printf("_%#s_", "hello");
	printf("\n%i\n", n);
	puts("");
	puts("space tests");
	n = printf("_% i_", 12345);
	printf("\n%i\n", n);
	n = printf("_% d_", 12345);
	printf("\n%i\n", n);
	n = printf("_% u_", 12345);
	printf("\n%i\n", n);
	n = printf("_% x_", 12345);
	printf("\n%i\n", n);
	n = printf("_% X_", 12345);
	printf("\n%i\n", n);
	n = printf("_% c_", 'c');
	printf("\n%i\n", n);
	n = printf("_% s_", "hello");
	printf("\n%i\n", n);
	puts("");
	puts("width tests");
	n = printf("_%8i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%8d_", 12345);
	printf("\n%i\n", n);
	n = printf("_%8u_", 12345);
	printf("\n%i\n", n);
	n = printf("_%8x_", 12345);
	printf("\n%i\n", n);
	n = printf("_%8X_", 12345);
	printf("\n%i\n", n);
	n = printf("_%8c_", 'c');
	printf("\n%i\n", n);
	n = printf("_%8s_", "hello");
	printf("\n%i\n", n);
	puts("");
	puts("- tests");
	n = printf("_%-8i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%-8d_", 12345);
	printf("\n%i\n", n);
	n = printf("_%-8u_", 12345);
	printf("\n%i\n", n);
	n = printf("_%-8x_", 12345);
	printf("\n%i\n", n);
	n = printf("_%-8X_", 12345);
	printf("\n%i\n", n);
	n = printf("_%-8c_", 'c');
	printf("\n%i\n", n);
	n = printf("_%-8s_", "hello");
	printf("\n%i\n", n);
	puts("");
	puts("0 tests");
	n = printf("_%08i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%08d_", 12345);
	printf("\n%i\n", n);
	n = printf("_%08u_", 12345);
	printf("\n%i\n", n);
	n = printf("_%08x_", 12345);
	printf("\n%i\n", n);
	n = printf("_%08X_", 12345);
	printf("\n%i\n", n);
	n = printf("_%08c_", 'c');
	printf("\n%i\n", n);
	n = printf("_%08s_", "hello");
	printf("\n%i\n", n);
	puts("");
	puts("width + precision tests");
	n = printf("_%#+12.6i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%#+12.14i_", 12345);
	printf("\n%i\n", n);
	puts("");
	puts("precision tests");
	n = printf("_%.8i_", 12345);
	printf("\n%i\n", n);
	n = printf("_%.8d_", 12345);
	printf("\n%i\n", n);
	n = printf("_%.8u_", 12345);
	printf("\n%i\n", n);
	n = printf("_%.8x_", 12345);
	printf("\n%i\n", n);
	n = printf("_%.8X_", 12345);
	printf("\n%i\n", n);
	n = printf("_%.8c_", 'c');
	printf("\n%i\n", n);
	n = printf("_%.8s_", "hello");
	printf("\n%i\n", n);
	n = printf("_%.4s_", "hello");
	printf("\n%i\n", n);
	puts("");
	puts("Wrong order");
	n = printf("_%5+i", 123);
	printf("\n%i\n", n);
	n = printf("_%5#i", 123);
	printf("\n%i\n", n);
	n = printf("_%.2 i", 123);
	printf("\n%i\n", n);
}
